/* 
 * 6.0-OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// AuditPublishdocReqRecipient
    /// </summary>
    [DataContract]
    public partial class AuditPublishdocReqRecipient :  IEquatable<AuditPublishdocReqRecipient>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditPublishdocReqRecipient" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuditPublishdocReqRecipient() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditPublishdocReqRecipient" /> class.
        /// </summary>
        /// <param name="recvareaid">发送目录 (required).</param>
        /// <param name="dstdocname">交换目的位置 (required).</param>
        public AuditPublishdocReqRecipient(string recvareaid = default(string), string dstdocname = default(string))
        {
            this.Recvareaid = recvareaid;
            this.Dstdocname = dstdocname;
        }
        
        /// <summary>
        /// 发送目录
        /// </summary>
        /// <value>发送目录</value>
        [DataMember(Name="recvareaid", EmitDefaultValue=false)]
        public string Recvareaid { get; set; }

        /// <summary>
        /// 交换目的位置
        /// </summary>
        /// <value>交换目的位置</value>
        [DataMember(Name="dstdocname", EmitDefaultValue=false)]
        public string Dstdocname { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AuditPublishdocReqRecipient {\n");
            sb.Append("  Recvareaid: ").Append(Recvareaid).Append("\n");
            sb.Append("  Dstdocname: ").Append(Dstdocname).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuditPublishdocReqRecipient);
        }

        /// <summary>
        /// Returns true if AuditPublishdocReqRecipient instances are equal
        /// </summary>
        /// <param name="input">Instance of AuditPublishdocReqRecipient to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuditPublishdocReqRecipient input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Recvareaid == input.Recvareaid ||
                    (this.Recvareaid != null &&
                    this.Recvareaid.Equals(input.Recvareaid))
                ) && 
                (
                    this.Dstdocname == input.Dstdocname ||
                    (this.Dstdocname != null &&
                    this.Dstdocname.Equals(input.Dstdocname))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Recvareaid != null)
                    hashCode = hashCode * 59 + this.Recvareaid.GetHashCode();
                if (this.Dstdocname != null)
                    hashCode = hashCode * 59 + this.Dstdocname.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
