/* 
 * 6.0-OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// Auth1GetvcodeRes
    /// </summary>
    [DataContract]
    public partial class Auth1GetvcodeRes :  IEquatable<Auth1GetvcodeRes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Auth1GetvcodeRes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Auth1GetvcodeRes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Auth1GetvcodeRes" /> class.
        /// </summary>
        /// <param name="uuid">验证码唯一标识 (required).</param>
        /// <param name="vcode">编码后的验证码字符串 (required).</param>
        public Auth1GetvcodeRes(string uuid = default(string), string vcode = default(string))
        {
            this.Uuid = uuid;
            this.Vcode = vcode;
        }
        
        /// <summary>
        /// 验证码唯一标识
        /// </summary>
        /// <value>验证码唯一标识</value>
        [DataMember(Name="uuid", EmitDefaultValue=false)]
        public string Uuid { get; set; }

        /// <summary>
        /// 编码后的验证码字符串
        /// </summary>
        /// <value>编码后的验证码字符串</value>
        [DataMember(Name="vcode", EmitDefaultValue=false)]
        public string Vcode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Auth1GetvcodeRes {\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  Vcode: ").Append(Vcode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Auth1GetvcodeRes);
        }

        /// <summary>
        /// Returns true if Auth1GetvcodeRes instances are equal
        /// </summary>
        /// <param name="input">Instance of Auth1GetvcodeRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Auth1GetvcodeRes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Uuid == input.Uuid ||
                    (this.Uuid != null &&
                    this.Uuid.Equals(input.Uuid))
                ) && 
                (
                    this.Vcode == input.Vcode ||
                    (this.Vcode != null &&
                    this.Vcode.Equals(input.Vcode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Uuid != null)
                    hashCode = hashCode * 59 + this.Uuid.GetHashCode();
                if (this.Vcode != null)
                    hashCode = hashCode * 59 + this.Vcode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
