/* 
 * 6.0-OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// Auth1GetbyticketReq
    /// </summary>
    [DataContract]
    public partial class Auth1GetbyticketReq :  IEquatable<Auth1GetbyticketReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Auth1GetbyticketReq" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Auth1GetbyticketReq() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Auth1GetbyticketReq" /> class.
        /// </summary>
        /// <param name="ticket">auth服务器返回的ticket票据，用来向token服务器请求token (required).</param>
        /// <param name="service">请求ticket时的service名称 (required).</param>
        public Auth1GetbyticketReq(string ticket = default(string), string service = default(string))
        {
            this.Ticket = ticket;
            this.Service = service;
        }
        
        /// <summary>
        /// auth服务器返回的ticket票据，用来向token服务器请求token
        /// </summary>
        /// <value>auth服务器返回的ticket票据，用来向token服务器请求token</value>
        [DataMember(Name="ticket", EmitDefaultValue=false)]
        public string Ticket { get; set; }

        /// <summary>
        /// 请求ticket时的service名称
        /// </summary>
        /// <value>请求ticket时的service名称</value>
        [DataMember(Name="service", EmitDefaultValue=false)]
        public string Service { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Auth1GetbyticketReq {\n");
            sb.Append("  Ticket: ").Append(Ticket).Append("\n");
            sb.Append("  Service: ").Append(Service).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Auth1GetbyticketReq);
        }

        /// <summary>
        /// Returns true if Auth1GetbyticketReq instances are equal
        /// </summary>
        /// <param name="input">Instance of Auth1GetbyticketReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Auth1GetbyticketReq input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Ticket == input.Ticket ||
                    (this.Ticket != null &&
                    this.Ticket.Equals(input.Ticket))
                ) && 
                (
                    this.Service == input.Service ||
                    (this.Service != null &&
                    this.Service.Equals(input.Service))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Ticket != null)
                    hashCode = hashCode * 59 + this.Ticket.GetHashCode();
                if (this.Service != null)
                    hashCode = hashCode * 59 + this.Service.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
