/* 
 * OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// DirCreateRes
    /// </summary>
    [DataContract]
    public partial class DirCreateRes :  IEquatable<DirCreateRes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DirCreateRes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DirCreateRes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DirCreateRes" /> class.
        /// </summary>
        /// <param name="docid">创建的目录的gns路径 (required).</param>
        /// <param name="rev">数据变化标识 (required).</param>
        /// <param name="modified">创建时间，UTC时间，此为服务器时间 (required).</param>
        /// <param name="createTime">目录创建的服务端时间 (required).</param>
        /// <param name="creator">目录创建者 (required).</param>
        /// <param name="editor">目录修改者 (required).</param>
        /// <param name="name">UTF8编码，仅当ondup为2时才返回.</param>
        public DirCreateRes(string docid = default(string), string rev = default(string), long? modified = default(long?), long? createTime = default(long?), string creator = default(string), string editor = default(string), string name = default(string))
        {
            this.Docid = docid;
            this.Rev = rev;
            this.Modified = modified;
            this.CreateTime = createTime;
            this.Creator = creator;
            this.Editor = editor;
            this.Name = name;
        }
        
        /// <summary>
        /// 创建的目录的gns路径
        /// </summary>
        /// <value>创建的目录的gns路径</value>
        [DataMember(Name="docid", EmitDefaultValue=false)]
        public string Docid { get; set; }

        /// <summary>
        /// 数据变化标识
        /// </summary>
        /// <value>数据变化标识</value>
        [DataMember(Name="rev", EmitDefaultValue=false)]
        public string Rev { get; set; }

        /// <summary>
        /// 创建时间，UTC时间，此为服务器时间
        /// </summary>
        /// <value>创建时间，UTC时间，此为服务器时间</value>
        [DataMember(Name="modified", EmitDefaultValue=false)]
        public long? Modified { get; set; }

        /// <summary>
        /// 目录创建的服务端时间
        /// </summary>
        /// <value>目录创建的服务端时间</value>
        [DataMember(Name="create_time", EmitDefaultValue=false)]
        public long? CreateTime { get; set; }

        /// <summary>
        /// 目录创建者
        /// </summary>
        /// <value>目录创建者</value>
        [DataMember(Name="creator", EmitDefaultValue=false)]
        public string Creator { get; set; }

        /// <summary>
        /// 目录修改者
        /// </summary>
        /// <value>目录修改者</value>
        [DataMember(Name="editor", EmitDefaultValue=false)]
        public string Editor { get; set; }

        /// <summary>
        /// UTF8编码，仅当ondup为2时才返回
        /// </summary>
        /// <value>UTF8编码，仅当ondup为2时才返回</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DirCreateRes {\n");
            sb.Append("  Docid: ").Append(Docid).Append("\n");
            sb.Append("  Rev: ").Append(Rev).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  Creator: ").Append(Creator).Append("\n");
            sb.Append("  Editor: ").Append(Editor).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DirCreateRes);
        }

        /// <summary>
        /// Returns true if DirCreateRes instances are equal
        /// </summary>
        /// <param name="input">Instance of DirCreateRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DirCreateRes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Docid == input.Docid ||
                    (this.Docid != null &&
                    this.Docid.Equals(input.Docid))
                ) && 
                (
                    this.Rev == input.Rev ||
                    (this.Rev != null &&
                    this.Rev.Equals(input.Rev))
                ) && 
                (
                    this.Modified == input.Modified ||
                    (this.Modified != null &&
                    this.Modified.Equals(input.Modified))
                ) && 
                (
                    this.CreateTime == input.CreateTime ||
                    (this.CreateTime != null &&
                    this.CreateTime.Equals(input.CreateTime))
                ) && 
                (
                    this.Creator == input.Creator ||
                    (this.Creator != null &&
                    this.Creator.Equals(input.Creator))
                ) && 
                (
                    this.Editor == input.Editor ||
                    (this.Editor != null &&
                    this.Editor.Equals(input.Editor))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Docid != null)
                    hashCode = hashCode * 59 + this.Docid.GetHashCode();
                if (this.Rev != null)
                    hashCode = hashCode * 59 + this.Rev.GetHashCode();
                if (this.Modified != null)
                    hashCode = hashCode * 59 + this.Modified.GetHashCode();
                if (this.CreateTime != null)
                    hashCode = hashCode * 59 + this.CreateTime.GetHashCode();
                if (this.Creator != null)
                    hashCode = hashCode * 59 + this.Creator.GetHashCode();
                if (this.Editor != null)
                    hashCode = hashCode * 59 + this.Editor.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
