/* 
 * OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// DirSizeReq
    /// </summary>
    [DataContract]
    public partial class DirSizeReq :  IEquatable<DirSizeReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DirSizeReq" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DirSizeReq() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DirSizeReq" /> class.
        /// </summary>
        /// <param name="docid">目录/文件gns路径（列举协议返回） (required).</param>
        /// <param name="onlyrecycle">- 默认为false  - 对于非顶级目录，参数onlyrecycle无影响  - 对顶级目录： 如果为false，统计整个顶级目录的大小；如果为true，只统计其中回收站的大小  .</param>
        public DirSizeReq(string docid = default(string), bool? onlyrecycle = default(bool?))
        {
            this.Docid = docid;
            this.Onlyrecycle = onlyrecycle;
        }
        
        /// <summary>
        /// 目录/文件gns路径（列举协议返回）
        /// </summary>
        /// <value>目录/文件gns路径（列举协议返回）</value>
        [DataMember(Name="docid", EmitDefaultValue=false)]
        public string Docid { get; set; }

        /// <summary>
        /// - 默认为false  - 对于非顶级目录，参数onlyrecycle无影响  - 对顶级目录： 如果为false，统计整个顶级目录的大小；如果为true，只统计其中回收站的大小  
        /// </summary>
        /// <value>- 默认为false  - 对于非顶级目录，参数onlyrecycle无影响  - 对顶级目录： 如果为false，统计整个顶级目录的大小；如果为true，只统计其中回收站的大小  </value>
        [DataMember(Name="onlyrecycle", EmitDefaultValue=false)]
        public bool? Onlyrecycle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DirSizeReq {\n");
            sb.Append("  Docid: ").Append(Docid).Append("\n");
            sb.Append("  Onlyrecycle: ").Append(Onlyrecycle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DirSizeReq);
        }

        /// <summary>
        /// Returns true if DirSizeReq instances are equal
        /// </summary>
        /// <param name="input">Instance of DirSizeReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DirSizeReq input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Docid == input.Docid ||
                    (this.Docid != null &&
                    this.Docid.Equals(input.Docid))
                ) && 
                (
                    this.Onlyrecycle == input.Onlyrecycle ||
                    (this.Onlyrecycle != null &&
                    this.Onlyrecycle.Equals(input.Onlyrecycle))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Docid != null)
                    hashCode = hashCode * 59 + this.Docid.GetHashCode();
                if (this.Onlyrecycle != null)
                    hashCode = hashCode * 59 + this.Onlyrecycle.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
