/* 
 * OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// Entrydoc2GetdocquotaRes
    /// </summary>
    [DataContract]
    public partial class Entrydoc2GetdocquotaRes :  IEquatable<Entrydoc2GetdocquotaRes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Entrydoc2GetdocquotaRes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Entrydoc2GetdocquotaRes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Entrydoc2GetdocquotaRes" /> class.
        /// </summary>
        /// <param name="quota">配额 (required).</param>
        /// <param name="used">已用空间 (required).</param>
        public Entrydoc2GetdocquotaRes(long? quota = default(long?), long? used = default(long?))
        {
            this.Quota = quota;
            this.Used = used;
        }
        
        /// <summary>
        /// 配额
        /// </summary>
        /// <value>配额</value>
        [DataMember(Name="quota", EmitDefaultValue=false)]
        public long? Quota { get; set; }

        /// <summary>
        /// 已用空间
        /// </summary>
        /// <value>已用空间</value>
        [DataMember(Name="used", EmitDefaultValue=false)]
        public long? Used { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Entrydoc2GetdocquotaRes {\n");
            sb.Append("  Quota: ").Append(Quota).Append("\n");
            sb.Append("  Used: ").Append(Used).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Entrydoc2GetdocquotaRes);
        }

        /// <summary>
        /// Returns true if Entrydoc2GetdocquotaRes instances are equal
        /// </summary>
        /// <param name="input">Instance of Entrydoc2GetdocquotaRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Entrydoc2GetdocquotaRes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Quota == input.Quota ||
                    (this.Quota != null &&
                    this.Quota.Equals(input.Quota))
                ) && 
                (
                    this.Used == input.Used ||
                    (this.Used != null &&
                    this.Used.Equals(input.Used))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Quota != null)
                    hashCode = hashCode * 59 + this.Quota.GetHashCode();
                if (this.Used != null)
                    hashCode = hashCode * 59 + this.Used.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
