/* 
 * OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// FileOsuploadrefreshRes
    /// </summary>
    [DataContract]
    public partial class FileOsuploadrefreshRes :  IEquatable<FileOsuploadrefreshRes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileOsuploadrefreshRes" /> class.
        /// </summary>
        /// <param name="uploadid">标识本次Multipart Upload事件.</param>
        /// <param name="authrequest">- authrequest[0]：请求方法  - authrequest[1]: 待上传的资源URL  - authrequest[2]及以后项：请求头；若请求时reqmethod的值为“POST”，则为POST表单域的项，格式为“key: value”.</param>
        public FileOsuploadrefreshRes(string uploadid = default(string), List<string> authrequest = default(List<string>))
        {
            this.Uploadid = uploadid;
            this.Authrequest = authrequest;
        }
        
        /// <summary>
        /// 标识本次Multipart Upload事件
        /// </summary>
        /// <value>标识本次Multipart Upload事件</value>
        [DataMember(Name="uploadid", EmitDefaultValue=false)]
        public string Uploadid { get; set; }

        /// <summary>
        /// - authrequest[0]：请求方法  - authrequest[1]: 待上传的资源URL  - authrequest[2]及以后项：请求头；若请求时reqmethod的值为“POST”，则为POST表单域的项，格式为“key: value”
        /// </summary>
        /// <value>- authrequest[0]：请求方法  - authrequest[1]: 待上传的资源URL  - authrequest[2]及以后项：请求头；若请求时reqmethod的值为“POST”，则为POST表单域的项，格式为“key: value”</value>
        [DataMember(Name="authrequest", EmitDefaultValue=false)]
        public List<string> Authrequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileOsuploadrefreshRes {\n");
            sb.Append("  Uploadid: ").Append(Uploadid).Append("\n");
            sb.Append("  Authrequest: ").Append(Authrequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FileOsuploadrefreshRes);
        }

        /// <summary>
        /// Returns true if FileOsuploadrefreshRes instances are equal
        /// </summary>
        /// <param name="input">Instance of FileOsuploadrefreshRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileOsuploadrefreshRes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Uploadid == input.Uploadid ||
                    (this.Uploadid != null &&
                    this.Uploadid.Equals(input.Uploadid))
                ) && 
                (
                    this.Authrequest == input.Authrequest ||
                    this.Authrequest != null &&
                    input.Authrequest != null &&
                    this.Authrequest.SequenceEqual(input.Authrequest)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Uploadid != null)
                    hashCode = hashCode * 59 + this.Uploadid.GetHashCode();
                if (this.Authrequest != null)
                    hashCode = hashCode * 59 + this.Authrequest.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
