/* 
 * OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// FilePlayinfoReq
    /// </summary>
    [DataContract]
    public partial class FilePlayinfoReq :  IEquatable<FilePlayinfoReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilePlayinfoReq" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FilePlayinfoReq() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FilePlayinfoReq" /> class.
        /// </summary>
        /// <param name="definition">视频画质（音频音质），为空默认为原始画质    有效值：空； od；sd    注：对于视频，od表示原始画质，sd表示标清；对于音频，sd请求无效.</param>
        /// <param name="docid">文件gns路径（列举协议返回） (required).</param>
        /// <param name="rev">版本号，为空默认获取最新版本.</param>
        public FilePlayinfoReq(string definition = default(string), string docid = default(string), string rev = default(string))
        {
            this.Docid = docid;
            this.Definition = definition;
            this.Rev = rev;
        }
        
        /// <summary>
        /// 视频画质（音频音质），为空默认为原始画质    有效值：空； od；sd    注：对于视频，od表示原始画质，sd表示标清；对于音频，sd请求无效
        /// </summary>
        /// <value>视频画质（音频音质），为空默认为原始画质    有效值：空； od；sd    注：对于视频，od表示原始画质，sd表示标清；对于音频，sd请求无效</value>
        [DataMember(Name="definition", EmitDefaultValue=false)]
        public string Definition { get; set; }

        /// <summary>
        /// 文件gns路径（列举协议返回）
        /// </summary>
        /// <value>文件gns路径（列举协议返回）</value>
        [DataMember(Name="docid", EmitDefaultValue=false)]
        public string Docid { get; set; }

        /// <summary>
        /// 版本号，为空默认获取最新版本
        /// </summary>
        /// <value>版本号，为空默认获取最新版本</value>
        [DataMember(Name="rev", EmitDefaultValue=false)]
        public string Rev { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FilePlayinfoReq {\n");
            sb.Append("  Definition: ").Append(Definition).Append("\n");
            sb.Append("  Docid: ").Append(Docid).Append("\n");
            sb.Append("  Rev: ").Append(Rev).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FilePlayinfoReq);
        }

        /// <summary>
        /// Returns true if FilePlayinfoReq instances are equal
        /// </summary>
        /// <param name="input">Instance of FilePlayinfoReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FilePlayinfoReq input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Definition == input.Definition ||
                    (this.Definition != null &&
                    this.Definition.Equals(input.Definition))
                ) && 
                (
                    this.Docid == input.Docid ||
                    (this.Docid != null &&
                    this.Docid.Equals(input.Docid))
                ) && 
                (
                    this.Rev == input.Rev ||
                    (this.Rev != null &&
                    this.Rev.Equals(input.Rev))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Definition != null)
                    hashCode = hashCode * 59 + this.Definition.GetHashCode();
                if (this.Docid != null)
                    hashCode = hashCode * 59 + this.Docid.GetHashCode();
                if (this.Rev != null)
                    hashCode = hashCode * 59 + this.Rev.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
