/* 
 * 6.0-OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// FileDeletecommentReq
    /// </summary>
    [DataContract]
    public partial class FileDeletecommentReq :  IEquatable<FileDeletecommentReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileDeletecommentReq" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FileDeletecommentReq() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FileDeletecommentReq" /> class.
        /// </summary>
        /// <param name="commentid">评论id（由获取文件评论协议返回） (required).</param>
        /// <param name="docid">文件gns路径（列举协议返回） (required).</param>
        public FileDeletecommentReq(long? commentid = default(long?), string docid = default(string))
        {
            this.Commentid = commentid;
            this.Docid = docid;
        }
        
        /// <summary>
        /// 评论id（由获取文件评论协议返回）
        /// </summary>
        /// <value>评论id（由获取文件评论协议返回）</value>
        [DataMember(Name="commentid", EmitDefaultValue=false)]
        public long? Commentid { get; set; }

        /// <summary>
        /// 文件gns路径（列举协议返回）
        /// </summary>
        /// <value>文件gns路径（列举协议返回）</value>
        [DataMember(Name="docid", EmitDefaultValue=false)]
        public string Docid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileDeletecommentReq {\n");
            sb.Append("  Commentid: ").Append(Commentid).Append("\n");
            sb.Append("  Docid: ").Append(Docid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FileDeletecommentReq);
        }

        /// <summary>
        /// Returns true if FileDeletecommentReq instances are equal
        /// </summary>
        /// <param name="input">Instance of FileDeletecommentReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileDeletecommentReq input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Commentid == input.Commentid ||
                    (this.Commentid != null &&
                    this.Commentid.Equals(input.Commentid))
                ) && 
                (
                    this.Docid == input.Docid ||
                    (this.Docid != null &&
                    this.Docid.Equals(input.Docid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Commentid != null)
                    hashCode = hashCode * 59 + this.Commentid.GetHashCode();
                if (this.Docid != null)
                    hashCode = hashCode * 59 + this.Docid.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
