/* 
 * 6.0-OpenDoc_API-文档访问
 *
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"  
 *
 * The version of the OpenAPI document: 6.0.10
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AnyShareSDK.Client.OpenAPIDateConverter;

namespace AnyShareSDK.Model
{
    /// <summary>
    /// FileOsdownloadRes
    /// </summary>
    [DataContract]
    public partial class FileOsdownloadRes :  IEquatable<FileOsdownloadRes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileOsdownloadRes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FileOsdownloadRes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FileOsdownloadRes" /> class.
        /// </summary>
        /// <param name="needWatermark">是否是下载水印文件 (required).</param>
        /// <param name="authrequest">- authrequest[0]：请求方法 - authrequest[1]：资源URL - authrequest[2]（如果存在）及以后项为http请求的headers，如自定义date，Content-type等，格式为“key: value” (required).</param>
        /// <param name="clientMtime">由客户端设置的文件本地修改时间 下载第0块时返回，若未设置，返回modified的值 (required).</param>
        /// <param name="editor">编辑者名称， UTF8编码 (required).</param>
        /// <param name="modified">上传时间， UTC时间，此为上传版本时的服务器时间 (required).</param>
        /// <param name="name">文件的当前名称，UTF8编码 (required).</param>
        /// <param name="rev">文件版本号 (required).</param>
        /// <param name="size">当前下载版本的总大小 (required).</param>
        public FileOsdownloadRes(bool? needWatermark = default(bool?), List<string> authrequest = default(List<string>), long? clientMtime = default(long?), string editor = default(string), long? modified = default(long?), string name = default(string), string rev = default(string), long? size = default(long?))
        {
            this.NeedWatermark = needWatermark;
            this.Authrequest = authrequest;
            this.ClientMtime = clientMtime;
            this.Editor = editor;
            this.Modified = modified;
            this.Name = name;
            this.Rev = rev;
            this.Size = size;
        }
        
        /// <summary>
        /// 是否是下载水印文件
        /// </summary>
        /// <value>是否是下载水印文件</value>
        [DataMember(Name="need_watermark", EmitDefaultValue=false)]
        public bool? NeedWatermark { get; set; }

        /// <summary>
        /// - authrequest[0]：请求方法 - authrequest[1]：资源URL - authrequest[2]（如果存在）及以后项为http请求的headers，如自定义date，Content-type等，格式为“key: value”
        /// </summary>
        /// <value>- authrequest[0]：请求方法 - authrequest[1]：资源URL - authrequest[2]（如果存在）及以后项为http请求的headers，如自定义date，Content-type等，格式为“key: value”</value>
        [DataMember(Name="authrequest", EmitDefaultValue=false)]
        public List<string> Authrequest { get; set; }

        /// <summary>
        /// 由客户端设置的文件本地修改时间 下载第0块时返回，若未设置，返回modified的值
        /// </summary>
        /// <value>由客户端设置的文件本地修改时间 下载第0块时返回，若未设置，返回modified的值</value>
        [DataMember(Name="client_mtime", EmitDefaultValue=false)]
        public long? ClientMtime { get; set; }

        /// <summary>
        /// 编辑者名称， UTF8编码
        /// </summary>
        /// <value>编辑者名称， UTF8编码</value>
        [DataMember(Name="editor", EmitDefaultValue=false)]
        public string Editor { get; set; }

        /// <summary>
        /// 上传时间， UTC时间，此为上传版本时的服务器时间
        /// </summary>
        /// <value>上传时间， UTC时间，此为上传版本时的服务器时间</value>
        [DataMember(Name="modified", EmitDefaultValue=false)]
        public long? Modified { get; set; }

        /// <summary>
        /// 文件的当前名称，UTF8编码
        /// </summary>
        /// <value>文件的当前名称，UTF8编码</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// 文件版本号
        /// </summary>
        /// <value>文件版本号</value>
        [DataMember(Name="rev", EmitDefaultValue=false)]
        public string Rev { get; set; }

        /// <summary>
        /// 当前下载版本的总大小
        /// </summary>
        /// <value>当前下载版本的总大小</value>
        [DataMember(Name="size", EmitDefaultValue=false)]
        public long? Size { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileOsdownloadRes {\n");
            sb.Append("  NeedWatermark: ").Append(NeedWatermark).Append("\n");
            sb.Append("  Authrequest: ").Append(Authrequest).Append("\n");
            sb.Append("  ClientMtime: ").Append(ClientMtime).Append("\n");
            sb.Append("  Editor: ").Append(Editor).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Rev: ").Append(Rev).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FileOsdownloadRes);
        }

        /// <summary>
        /// Returns true if FileOsdownloadRes instances are equal
        /// </summary>
        /// <param name="input">Instance of FileOsdownloadRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileOsdownloadRes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NeedWatermark == input.NeedWatermark ||
                    (this.NeedWatermark != null &&
                    this.NeedWatermark.Equals(input.NeedWatermark))
                ) && 
                (
                    this.Authrequest == input.Authrequest ||
                    this.Authrequest != null &&
                    input.Authrequest != null &&
                    this.Authrequest.SequenceEqual(input.Authrequest)
                ) && 
                (
                    this.ClientMtime == input.ClientMtime ||
                    (this.ClientMtime != null &&
                    this.ClientMtime.Equals(input.ClientMtime))
                ) && 
                (
                    this.Editor == input.Editor ||
                    (this.Editor != null &&
                    this.Editor.Equals(input.Editor))
                ) && 
                (
                    this.Modified == input.Modified ||
                    (this.Modified != null &&
                    this.Modified.Equals(input.Modified))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Rev == input.Rev ||
                    (this.Rev != null &&
                    this.Rev.Equals(input.Rev))
                ) && 
                (
                    this.Size == input.Size ||
                    (this.Size != null &&
                    this.Size.Equals(input.Size))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NeedWatermark != null)
                    hashCode = hashCode * 59 + this.NeedWatermark.GetHashCode();
                if (this.Authrequest != null)
                    hashCode = hashCode * 59 + this.Authrequest.GetHashCode();
                if (this.ClientMtime != null)
                    hashCode = hashCode * 59 + this.ClientMtime.GetHashCode();
                if (this.Editor != null)
                    hashCode = hashCode * 59 + this.Editor.GetHashCode();
                if (this.Modified != null)
                    hashCode = hashCode * 59 + this.Modified.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Rev != null)
                    hashCode = hashCode * 59 + this.Rev.GetHashCode();
                if (this.Size != null)
                    hashCode = hashCode * 59 + this.Size.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
